/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ConfidentialDAOInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "callbackHasBeenCalled"
      | "createProposal"
      | "getDecryptionRequestId"
      | "getProposal"
      | "getRevealStatus"
      | "hasVoted"
      | "isCallbackCalled"
      | "isRevealRequested"
      | "owner"
      | "proposalFee"
      | "proposals"
      | "protocolId"
      | "requestTallyReveal"
      | "resolveTallyCallback"
      | "setProposalFee"
      | "vote"
      | "withdrawFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CallbackFlagSet"
      | "DebugCallbackStep"
      | "DecryptionFulfilled"
      | "ProposalCreated"
      | "ProposalResolved"
      | "TallyRevealRequested"
      | "Voted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "callbackHasBeenCalled",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createProposal",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDecryptionRequestId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRevealStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isCallbackCalled",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isRevealRequested",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proposalFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proposals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestTallyReveal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveTallyCallback",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setProposalFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [BigNumberish, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "callbackHasBeenCalled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDecryptionRequestId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRevealStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isCallbackCalled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRevealRequested",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposalFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proposals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestTallyReveal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveTallyCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProposalFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
}

export namespace CallbackFlagSetEvent {
  export type InputTuple = [proposalId: BigNumberish];
  export type OutputTuple = [proposalId: bigint];
  export interface OutputObject {
    proposalId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DebugCallbackStepEvent {
  export type InputTuple = [step: string, proposalId: BigNumberish];
  export type OutputTuple = [step: string, proposalId: bigint];
  export interface OutputObject {
    step: string;
    proposalId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DecryptionFulfilledEvent {
  export type InputTuple = [requestID: BigNumberish];
  export type OutputTuple = [requestID: bigint];
  export interface OutputObject {
    requestID: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalCreatedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    creator: AddressLike,
    token: AddressLike,
    endTime: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    creator: string,
    token: string,
    endTime: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    creator: string;
    token: string;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalResolvedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    forVotes: BigNumberish,
    againstVotes: BigNumberish,
    abstainVotes: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    forVotes: bigint,
    againstVotes: bigint,
    abstainVotes: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    forVotes: bigint;
    againstVotes: bigint;
    abstainVotes: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TallyRevealRequestedEvent {
  export type InputTuple = [proposalId: BigNumberish, requestId: BigNumberish];
  export type OutputTuple = [proposalId: bigint, requestId: bigint];
  export interface OutputObject {
    proposalId: bigint;
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotedEvent {
  export type InputTuple = [proposalId: BigNumberish, voter: AddressLike];
  export type OutputTuple = [proposalId: bigint, voter: string];
  export interface OutputObject {
    proposalId: bigint;
    voter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ConfidentialDAO extends BaseContract {
  connect(runner?: ContractRunner | null): ConfidentialDAO;
  waitForDeployment(): Promise<this>;

  interface: ConfidentialDAOInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  callbackHasBeenCalled: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  createProposal: TypedContractMethod<
    [token: AddressLike, durationSeconds: BigNumberish],
    [void],
    "payable"
  >;

  getDecryptionRequestId: TypedContractMethod<
    [proposalId: BigNumberish],
    [bigint],
    "view"
  >;

  getProposal: TypedContractMethod<
    [proposalId: BigNumberish],
    [
      [string, string, bigint, boolean, bigint, bigint, bigint] & {
        creator: string;
        token: string;
        endTime: bigint;
        resolved: boolean;
        forVotes: bigint;
        againstVotes: bigint;
        abstainVotes: bigint;
      }
    ],
    "view"
  >;

  getRevealStatus: TypedContractMethod<
    [proposalId: BigNumberish],
    [
      [boolean, bigint, bigint, bigint, bigint] & {
        resolved: boolean;
        revealedFor: bigint;
        revealedAgainst: bigint;
        revealedAbstain: bigint;
        decryptionRequestId: bigint;
      }
    ],
    "view"
  >;

  hasVoted: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isCallbackCalled: TypedContractMethod<
    [proposalId: BigNumberish],
    [boolean],
    "view"
  >;

  isRevealRequested: TypedContractMethod<
    [proposalId: BigNumberish],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  proposalFee: TypedContractMethod<[], [bigint], "view">;

  proposals: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        string,
        string,
        string,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        creator: string;
        token: string;
        endTime: bigint;
        forVotes: string;
        againstVotes: string;
        abstainVotes: string;
        resolved: boolean;
        revealedFor: bigint;
        revealedAgainst: bigint;
        revealedAbstain: bigint;
        decryptionRequestId: bigint;
      }
    ],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  requestTallyReveal: TypedContractMethod<
    [proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  resolveTallyCallback: TypedContractMethod<
    [
      requestId: BigNumberish,
      cleartexts: BytesLike,
      decryptionProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setProposalFee: TypedContractMethod<
    [newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  vote: TypedContractMethod<
    [
      proposalId: BigNumberish,
      encryptedWeight: BytesLike,
      voteType: BigNumberish,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  withdrawFees: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "callbackHasBeenCalled"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "createProposal"
  ): TypedContractMethod<
    [token: AddressLike, durationSeconds: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getDecryptionRequestId"
  ): TypedContractMethod<[proposalId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getProposal"
  ): TypedContractMethod<
    [proposalId: BigNumberish],
    [
      [string, string, bigint, boolean, bigint, bigint, bigint] & {
        creator: string;
        token: string;
        endTime: bigint;
        resolved: boolean;
        forVotes: bigint;
        againstVotes: bigint;
        abstainVotes: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRevealStatus"
  ): TypedContractMethod<
    [proposalId: BigNumberish],
    [
      [boolean, bigint, bigint, bigint, bigint] & {
        resolved: boolean;
        revealedFor: bigint;
        revealedAgainst: bigint;
        revealedAbstain: bigint;
        decryptionRequestId: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isCallbackCalled"
  ): TypedContractMethod<[proposalId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isRevealRequested"
  ): TypedContractMethod<[proposalId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proposalFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "proposals"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        string,
        string,
        string,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        creator: string;
        token: string;
        endTime: bigint;
        forVotes: string;
        againstVotes: string;
        abstainVotes: string;
        resolved: boolean;
        revealedFor: bigint;
        revealedAgainst: bigint;
        revealedAbstain: bigint;
        decryptionRequestId: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "requestTallyReveal"
  ): TypedContractMethod<[proposalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveTallyCallback"
  ): TypedContractMethod<
    [
      requestId: BigNumberish,
      cleartexts: BytesLike,
      decryptionProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setProposalFee"
  ): TypedContractMethod<[newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<
    [
      proposalId: BigNumberish,
      encryptedWeight: BytesLike,
      voteType: BigNumberish,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "CallbackFlagSet"
  ): TypedContractEvent<
    CallbackFlagSetEvent.InputTuple,
    CallbackFlagSetEvent.OutputTuple,
    CallbackFlagSetEvent.OutputObject
  >;
  getEvent(
    key: "DebugCallbackStep"
  ): TypedContractEvent<
    DebugCallbackStepEvent.InputTuple,
    DebugCallbackStepEvent.OutputTuple,
    DebugCallbackStepEvent.OutputObject
  >;
  getEvent(
    key: "DecryptionFulfilled"
  ): TypedContractEvent<
    DecryptionFulfilledEvent.InputTuple,
    DecryptionFulfilledEvent.OutputTuple,
    DecryptionFulfilledEvent.OutputObject
  >;
  getEvent(
    key: "ProposalCreated"
  ): TypedContractEvent<
    ProposalCreatedEvent.InputTuple,
    ProposalCreatedEvent.OutputTuple,
    ProposalCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalResolved"
  ): TypedContractEvent<
    ProposalResolvedEvent.InputTuple,
    ProposalResolvedEvent.OutputTuple,
    ProposalResolvedEvent.OutputObject
  >;
  getEvent(
    key: "TallyRevealRequested"
  ): TypedContractEvent<
    TallyRevealRequestedEvent.InputTuple,
    TallyRevealRequestedEvent.OutputTuple,
    TallyRevealRequestedEvent.OutputObject
  >;
  getEvent(
    key: "Voted"
  ): TypedContractEvent<
    VotedEvent.InputTuple,
    VotedEvent.OutputTuple,
    VotedEvent.OutputObject
  >;

  filters: {
    "CallbackFlagSet(uint256)": TypedContractEvent<
      CallbackFlagSetEvent.InputTuple,
      CallbackFlagSetEvent.OutputTuple,
      CallbackFlagSetEvent.OutputObject
    >;
    CallbackFlagSet: TypedContractEvent<
      CallbackFlagSetEvent.InputTuple,
      CallbackFlagSetEvent.OutputTuple,
      CallbackFlagSetEvent.OutputObject
    >;

    "DebugCallbackStep(string,uint256)": TypedContractEvent<
      DebugCallbackStepEvent.InputTuple,
      DebugCallbackStepEvent.OutputTuple,
      DebugCallbackStepEvent.OutputObject
    >;
    DebugCallbackStep: TypedContractEvent<
      DebugCallbackStepEvent.InputTuple,
      DebugCallbackStepEvent.OutputTuple,
      DebugCallbackStepEvent.OutputObject
    >;

    "DecryptionFulfilled(uint256)": TypedContractEvent<
      DecryptionFulfilledEvent.InputTuple,
      DecryptionFulfilledEvent.OutputTuple,
      DecryptionFulfilledEvent.OutputObject
    >;
    DecryptionFulfilled: TypedContractEvent<
      DecryptionFulfilledEvent.InputTuple,
      DecryptionFulfilledEvent.OutputTuple,
      DecryptionFulfilledEvent.OutputObject
    >;

    "ProposalCreated(uint256,address,address,uint256)": TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;
    ProposalCreated: TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;

    "ProposalResolved(uint256,uint64,uint64,uint64)": TypedContractEvent<
      ProposalResolvedEvent.InputTuple,
      ProposalResolvedEvent.OutputTuple,
      ProposalResolvedEvent.OutputObject
    >;
    ProposalResolved: TypedContractEvent<
      ProposalResolvedEvent.InputTuple,
      ProposalResolvedEvent.OutputTuple,
      ProposalResolvedEvent.OutputObject
    >;

    "TallyRevealRequested(uint256,uint256)": TypedContractEvent<
      TallyRevealRequestedEvent.InputTuple,
      TallyRevealRequestedEvent.OutputTuple,
      TallyRevealRequestedEvent.OutputObject
    >;
    TallyRevealRequested: TypedContractEvent<
      TallyRevealRequestedEvent.InputTuple,
      TallyRevealRequestedEvent.OutputTuple,
      TallyRevealRequestedEvent.OutputObject
    >;

    "Voted(uint256,address)": TypedContractEvent<
      VotedEvent.InputTuple,
      VotedEvent.OutputTuple,
      VotedEvent.OutputObject
    >;
    Voted: TypedContractEvent<
      VotedEvent.InputTuple,
      VotedEvent.OutputTuple,
      VotedEvent.OutputObject
    >;
  };
}
